# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JIps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='127.0.0.1', max_length=20, verbose_name='主机或者服务器IP')),
                ('stat', models.IntegerField(default=0, verbose_name='状态|ip')),
                ('belongCate', models.CharField(default='host', max_length=20, verbose_name='IP所属类型')),
                ('text', models.CharField(default='预警信息', max_length=20, verbose_name='弹出text')),
            ],
            options={
                'verbose_name': 'Jtopo里面的IP',
            },
        ),
    ]
