# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 01:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jtopot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jips',
            name='add_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='添加时间'),
            preserve_default=False,
        ),
    ]
