# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-17 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jtopot', '0002_jips_add_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jips',
            old_name='text',
            new_name='tc_text',
        ),
    ]
