# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBase',
            fields=[
                ('event_name', models.CharField(blank=True, max_length=150, verbose_name='事件名')),
                ('event_cate', models.CharField(default='交通', max_length=50, verbose_name='事件类型')),
                ('event_src', models.CharField(default='0.0.0.0', max_length=20, verbose_name='泄露源')),
                ('to_server', models.CharField(default='0.0.0.0', max_length=20, verbose_name='流向IP')),
                ('port', models.CharField(default='443', max_length=20, verbose_name='端口')),
                ('happened_date', models.DateField(auto_now=True, verbose_name='发生日期')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': '事件',
            },
        ),
        migrations.CreateModel(
            name='EventDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_stat', models.CharField(blank=True, max_length=50, verbose_name='状态')),
                ('event_time', models.DateTimeField(auto_now=True, verbose_name='事件状态时间')),
                ('extra_add', models.TextField(default='', verbose_name='添加备注')),
                ('connect_person', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='状态参与人员')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.EventBase', verbose_name='事件')),
            ],
            options={
                'verbose_name': '事件详细',
            },
        ),
    ]
