# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-09 06:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShenFen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shenfen', models.CharField(blank=True, max_length=50, verbose_name='身份')),
                ('proty', models.IntegerField(blank=True, verbose_name='权限标志|/d')),
            ],
            options={
                'verbose_name': '用户身份表|固定填写',
            },
        ),
        migrations.RemoveField(
            model_name='projuser',
            name='shenfen',
        ),
        migrations.DeleteModel(
            name='ShenFen',
        ),
        migrations.AddField(
            model_name='usershenfen',
            name='webuser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='网站用户'),
        ),
    ]
